### ISSUE TITLE
YOUR regulargrid.interpn IS WRONG!!

### ISSUE THREAD

**Issue by dogod621** [JohannesBuchner/regulargrid#5]
At regulargrid.interpn  line 23:
  a = interp1d(q[j], a, axis=j, kind=method)(qi[j])

Please fix the axis error"axis=0 for any dimension at loop":
  a = interp1d(q[j], a, axis=0, kind=method)(qi[j])

**Comment by JohannesBuchner** [comment]
This package is outdated. Please use scipy.interpolate.RegularGridInterpolator instead: https://scipy.github.io/devdocs/generated/scipy.interpolate.RegularGridInterpolator.html 
It is more general, shorter, and much faster code.
